### ISSUE TITLE
Example "LoRaWan_OnBoardGPS_Air530.ino" stops working after some time

### ISSUE THREAD

**Issue by 505222621** [HelTecAutomation/CubeCell-Arduino#247]
Board: CubeCell HTCC-AB02S GPS
Example: LoRaWan_OnBoardGPS_Air530
After running for a few minutes in the open field, the code gets stuck in the GPS segment

**Comment by Mr-HaleYa** [comment]
are you using battery power?

**Comment by 505222621** [comment]
> are you using battery power?

no,using USB power

**Comment by rodri16** [comment]
Same problem here...

**Comment by 505222621** [comment]
> This is because it constantly starts and stops the GPS and there is a memory leak bug in the GPS.end() function that is fixed with this commit: [85c0c75](https://github.com/HelTecAutomation/CubeCell-Arduino/commit/85c0c7542b4496658624e578f45d187c321bc8ad)

yes,GPS.begin -> serial-begin : malloc(buf),no free(buf),change to global variable or serial-end :free(buf)
